### ISSUE TITLE
go2port update please v17.6.2 results in invalid go.vendor entries

### ISSUE THREAD

**Issue by halostatue** [amake/go2port#9]
I ran `go2port update please v17.6.2 --output Portfile` and things *looked* good, but `sudo port install` fails because of 404s on archives.

This doesn't entirely make sense for the initial failure (`aws-aws-sdk-go-v2-service-v1.17.6.tar.gz`), which is added to `go.vendors` as:

```
                    github.com/aws/aws-sdk-go-v2/service/sts \
                        lock    v1.17.6 \
                        rmd160  fe753b92389bbd2190892393f803bb179d68aa56 \
                        sha256  7367751f962c76e5d5f6785e99f7f4057df4d855de0187e3abbfc685151e9744 \
                        size    33440406 \
```

However, there are 26 entries in `go.vendors` which result in `size 14` and identical `rmd160`/`sha256` blocks, because it's all `404 Not Found`.

```
                    github.com/hashicorp/go-secure-stdlib/strutil \
                        lock    v0.1.2 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/hashicorp/go-secure-stdlib/parseutil \
                        lock    v0.1.7 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/hashicorp/go-secure-stdlib/mlock \
                        lock    v0.1.2 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/aws/aws-sdk-go-v2/service/ssooidc \
                        lock    v1.13.9 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/aws/aws-sdk-go-v2/service/sso \
                        lock    v1.11.26 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/aws/aws-sdk-go-v2/service/kms \
                        lock    v1.19.2 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/aws/aws-sdk-go-v2/service/internal/presigned-url \
                        lock    v1.9.20 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/aws/aws-sdk-go-v2/internal/ini \
                        lock    v1.3.27 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/aws/aws-sdk-go-v2/internal/endpoints \
                        lock    v2.4.20 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/aws/aws-sdk-go-v2/internal/configsources \
                        lock    v1.1.26 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/aws/aws-sdk-go-v2/feature/ec2/imds \
                        lock    v1.12.20 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/aws/aws-sdk-go-v2/credentials \
                        lock    v1.13.4 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/aws/aws-sdk-go-v2/config \
                        lock    v1.18.4 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/Azure/go-autorest/tracing \
                        lock    v0.6.0 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/Azure/go-autorest/logger \
                        lock    v0.2.1 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/Azure/go-autorest/autorest/validation \
                        lock    v0.3.1 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/Azure/go-autorest/autorest/to \
                        lock    v0.4.0 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/Azure/go-autorest/autorest/date \
                        lock    v0.3.0 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/Azure/go-autorest/autorest/azure/cli \
                        lock    v0.4.6 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/Azure/go-autorest/autorest/azure/auth \
                        lock    v0.5.11 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/Azure/go-autorest/autorest/adal \
                        lock    v0.9.21 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    github.com/Azure/go-autorest/autorest \
                        lock    v0.11.28 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    cloud.google.com/go/longrunning \
                        repo    github.com/googleapis/google-cloud-go \
                        lock    v0.4.1 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    cloud.google.com/go/kms \
                        repo    github.com/googleapis/google-cloud-go \
                        lock    v1.10.1 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    cloud.google.com/go/compute/metadata \
                        repo    github.com/googleapis/google-cloud-go \
                        lock    v0.2.3 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
                    cloud.google.com/go/compute \
                        repo    github.com/googleapis/google-cloud-go \
                        lock    v1.19.1 \
                        rmd160  be5792c0b99a324f2c6b525b3ad4850bf93ecd2f \
                        sha256  d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed \
                        size    14 \
```

I'm not sure if these issues are related, but something feels off, regardless, and I’m not sure where to begin.

I'm attaching the updated/generated [`Portfile`](https://github.com/amake/go2port/files/13968168/Portfile.txt) for reference.

**Comment by amake** [comment]
go2port uses its own very simple package-resolving logic (I don't know where the "real" logic is or whether it's reusable in an application like go2port). This logic can't handle submodule dependencies correctly.

For instance `cloud.google.com/go/kms` and `cloud.google.com/go/compute/metadata` both resolve to submodules in `github.com/googleapis/google-cloud-go`, but currently in MacPorts (via the golang-1.0 portgroup) both modules can only be manifested by a single revision of their containing repo.

This means that if the project wants versions of `cloud.google.com/go/kms` and `cloud.google.com/go/compute/metadata` that correspond to different commits in the repo, then you will get the "wrong" version for (at least) one of them. This essentially means that you aren't guaranteed to build your port from the right set of source files.

Sometimes you'll get lucky and everything will work fine. Some ports are built like this and seem to work fine, or maybe they're subtly buggy but no one has noticed.

So if you like to gamble like this, the trick to getting the portfile to work is:

- Remove any submodule dependencies and make sure there is a dependency on the parent repo as a whole. That means delete all `cloud.google.com/go/*` entries from `go.vendors` and leave just `cloud.google.com/go` (which happens to be there already; if it wasn't you'd need to add it manually).
- The same treatment is needed for `github.com/aws/aws-sdk-go-v2/*` (`github.com/aws/aws-sdk-go-v2` is already included, so no extra work needed)
- The same is needed for `github.com/hashicorp/go-secure-stdlib/*`, but here `github.com/hashicorp/go-secure-stdlib` is not included so that needs to be added manually. Poking around the tags for the specified submodules, I found that the tag v0.1.0 happens to represent the correct version for all three.
- `google.golang.org/protobuf` is hosted on go.googlesource.com, which can't serve stable tarballs, so that needs to be manually resolved to the GitHub mirror. I will add a special case to go2port to handle this because it's such a common dependency.

Thus you can see that go2port is really a hack that only works well when a project happens to have well-behaved dependencies. I'm sure it could be improved by someone who has better knowledge of golang dependency resolution, but that's not me.

The MacPorts project as a policy strongly discourages downloading dependencies at build time, but there are some golang ports that do so because getting the golang-1.0 portgroup and go2port to work for them is so cumbersome.

If you do want to go with go2port, I have manually applied the above fixes:

<details><summary>Manually fixed go.vendors</summary>

```
go.vendors          gopkg.in/yaml.v3 \
                        lock    v3.0.1 \
                        rmd160  e85ac1368fb7f9ef945b7fd7bd608a1f0d261c12 \
                        sha256  f3ea6be3f405ec25f8799773355aba54f8831d11f5315a01155bdc69b92eca7b \
                        size    91208 \
                    gopkg.in/yaml.v2 \
                        lock    v2.4.0 \
                        rmd160  66e9feb7944b3804efa63155ed9b618717b8955c \
                        sha256  72812077e7f20278003de6ab0d85053d89131d64c443f39115a022114fd032b6 \
                        size    73231 \
                    gopkg.in/warnings.v0 \
                        lock    v0.1.2 \
                        rmd160  e0245ded51f41ce8051ae561d1a0b844f4b8f181 \
                        sha256  547803dff3ec1c7adb69c411e7b3846595c3265d22a8888001661504d23bd4fb \
                        size    3772 \
                    gopkg.in/square/go-jose.v2 \
                        lock    v2.6.0 \
                        rmd160  56e581a46f0364551657e2b7698bd022973e9d7c \
                        sha256  565d45760f1ee44d3c076b9f5ee46e14e046c00304ddfab345fc48443fd6031c \
                        size    310376 \
                    gopkg.in/op/go-logging.v1 \
                        lock    b2cb9fa56473 \
                        rmd160  2621efba2352994d2b3a1541c853511b24884e54 \
                        sha256  73acfa44b0fe8e3074d173f04ce164e81b6996327d07d0bec0025df0491e4091 \
                        size    35888 \
                    gopkg.in/check.v1 \
                        lock    10cb98267c6c \
                        rmd160  465dcadb97762c84da6fb5f6d8352abe10445817 \
                        sha256  98ec7bd0dc7d4bcee7dcafe02efab29f14dc392f43b227e517beef064e9b6369 \
                        size    32368 \
                    gopkg.in/alexcesaro/statsd.v2 \
                        lock    v2.0.0 \
                        rmd160  5c1281833fb55b3c0b00e4a0e8df8e45da6978f9 \
                        sha256  5509ba3b2574f0f016acdcee17a1540bb05477bc0239441631481d2c65e0dd74 \
                        size    10681 \
                    google.golang.org/protobuf \
                        repo    github.com/protocolbuffers/protobuf-go \
                        lock    v1.30.0 \
                        rmd160  80cc9e6edacb19c225de4f8c07f3c5f79ac9e84a \
                        sha256  d4ac2c8ff456abc74679f4f37cc8d7aac195684f7698d2030fc5bfe14243b5fa \
                        size    1299719 \
                    google.golang.org/grpc \
                        repo    github.com/grpc/grpc-go \
                        lock    v1.56.3 \
                        rmd160  222680e38fbee551201c1bef9efc34c77e57959d \
                        sha256  6c82926722d6a09ea679d50636710a56ce61e21229ac74e77e5c248c9e875969 \
                        size    1944287 \
                    google.golang.org/genproto \
                        repo    github.com/googleapis/go-genproto \
                        lock    daa745c078e1 \
                        rmd160  d6ab558a809eae8cac1a0f24a4eea32758cf51b6 \
                        sha256  c4e5893c9cbd9213cde1e8eba48a9ba534ec2a2268decfbc42093f24321b1933 \
                        size    6013161 \
                    google.golang.org/appengine \
                        repo    github.com/golang/appengine \
                        lock    v1.6.7 \
                        rmd160  32e6de431630b8126df1d04e36eba2abb57626f1 \
                        sha256  3669d59598e4bd657ec079f151fab47b3aa130adfec35daeb05e079220970cd2 \
                        size    333026 \
                    google.golang.org/api \
                        repo    github.com/googleapis/google-api-go-client \
                        lock    v0.114.0 \
                        rmd160  789e72f5804dd930046a2f0269c328bb6390a0a0 \
                        sha256  0cdeba5d616dca0f94b42fec3ad37ced9bf37a2db3e9f60b6d5645358562a557 \
                        size    31373372 \
                    golang.org/x/tools \
                        lock    v0.6.0 \
                        rmd160  4b249b4a0a81358289599e3505f17490396d4d06 \
                        sha256  e064d0d45d4ca70abd87066b550137f985d487b424f8d58b39b6e6f4129dcea5 \
                        size    3307706 \
                    golang.org/x/time \
                        lock    v0.2.0 \
                        rmd160  c12876e3e3a580b718470eae1a8048c2174b6e53 \
                        sha256  665a1c974063e86fb50992a262421cbfd14fc54725c60a5386bd83ecafa8efff \
                        size    12162 \
                    golang.org/x/text \
                        lock    v0.14.0 \
                        rmd160  e26a72d542901d19f6dde4e07746f72206fb8701 \
                        sha256  ef54709caaafdd8b27ce3d5f7c53408f11bc5fd1688c1c4f328de8ed268b3188 \
                        size    8972503 \
                    golang.org/x/term \
                        lock    v0.15.0 \
                        rmd160  55c1bd4787d58c6d2ea19a1ba3a3ccd6b091fa14 \
                        sha256  747ef42b61096cc3e763ec084a821c789b464cbe51e043bebf0d9af75a062972 \
                        size    14740 \
                    golang.org/x/sys \
                        lock    v0.15.0 \
                        rmd160  84270c5ffe3cd1540ccf8b8f19120cbdb117f848 \
                        sha256  183f3870369e62e0ecaf378b5ef3d335e7fcebfd3ebfb81a0576b424a941476f \
                        size    1443915 \
                    golang.org/x/sync \
                        lock    v0.1.0 \
                        rmd160  bf68702d961107a225cce561701852f129f16a3d \
                        sha256  50a67a11e715a61c022f218604adc63e61684de5f5db2330741077439c4ce68f \
                        size    19355 \
                    golang.org/x/oauth2 \
                        lock    v0.7.0 \
                        rmd160  7cc03af8875a7394bf2f017dc8b6ceeab0b0f7bf \
                        sha256  19fc8f8eba76cfb58ab6fe0dc857e03f3aaa4cfd92c28ee60d555fe6b7efeb1e \
                        size    87771 \
                    golang.org/x/net \
                        lock    v0.17.0 \
                        rmd160  3e1d150fbede0be1af1b248e536930de2446ef0e \
                        sha256  6bb73c8f9eef753cab2b18d4af7893ff955b4427c6d34c8f4d7c9127d09abcc0 \
                        size    1456371 \
                    golang.org/x/lint \
                        lock    83fdc39ff7b5 \
                        rmd160  f43d7ee34fb9b83724fa696529d85b1410610a2d \
                        sha256  818bfcaf2d3a7d3c6e93a76e5b4f92f8670721f4517ed814755bdbc34a88cefa \
                        size    31886 \
                    golang.org/x/crypto \
                        lock    v0.17.0 \
                        rmd160  b42d588c4aa930e1d70d67b75a9a3f20a613536e \
                        sha256  a559bc5b604090ff2ad6040e8207d79a969ff3017f9e61d2eb0df774ae3b47f4 \
                        size    1809435 \
                    go.uber.org/goleak \
                        repo    github.com/uber-go/goleak \
                        lock    v1.1.10 \
                        rmd160  c14302ab00c2b601bba06dd46b064e403179046f \
                        sha256  06180861954746fee9f7b43329bb5fa3e1ecc08eceec2ef0876438d9bbc8e479 \
                        size    12103 \
                    go.uber.org/automaxprocs \
                        repo    github.com/uber-go/automaxprocs \
                        lock    v1.4.0 \
                        rmd160  52804d713060b31d329cf60c45e6429dbc2e553b \
                        sha256  725c62bbddf53165709b75c1a4ba7055e3424f21a129b90ce4632d3ea94910fb \
                        size    19646 \
                    go.uber.org/atomic \
                        repo    github.com/uber-go/atomic \
                        lock    v1.10.0 \
                        rmd160  3b3e329c78468d0b4711b28f323069a1d6afbeec \
                        sha256  c03c44af9133c1c06829842b6db2a1bff49818d1cb96c709d65301651f4bc390 \
                        size    23092 \
                    go.opencensus.io \
                        repo    github.com/census-instrumentation/opencensus-go \
                        lock    v0.24.0 \
                        rmd160  3ff78177f0e279b4c2f8aaa474fd747bbcb1e89c \
                        sha256  7a88d68f99dd9ee8dd460e954f98b158629a44ba85ffc8239e13a60e0802e57a \
                        size    176686 \
                    github.com/zeebo/pcg \
                        lock    v1.0.1 \
                        rmd160  43108da77bbe32f68199761edfc00c1a1a0c554a \
                        sha256  672183d22d92907b80f32399817819ce7021d2741e5f393b57f593f2b04b08cc \
                        size    6083 \
                    github.com/zeebo/blake3 \
                        lock    v0.2.3 \
                        rmd160  9786a3b0afcaeccb9fd1c602cc464f83a06ef556 \
                        sha256  9d19ce0e1513c70b179f98fe9f84b6cbf0fda25236ff8cdb6b2c80b73c74f9e3 \
                        size    110886 \
                    github.com/zeebo/assert \
                        lock    v1.1.0 \
                        rmd160  b7002ecb6d9a41a256dc151a08a5c4768e4f25f6 \
                        sha256  c80ccd3b288569574caa5cd90b52f145f7b64eaae18ba34ef3566156d87d6149 \
                        size    883 \
                    github.com/vmihailenco/tagparser \
                        lock    v2.0.0 \
                        rmd160  bc9aec6b8e0daeceddff97192b7156cd7a370ef4 \
                        sha256  c40bc0935d68707ec8c7f96c544c0c52a7740ab0dd6a4a6939a951f1fe69c3dd \
                        size    3690 \
                    github.com/vmihailenco/msgpack \
                        lock    v5.3.5 \
                        rmd160  470d702bacb6e2bb75faf8b3a4a237adeb5f7dec \
                        sha256  8bee1baa761701e1eb01cff324119720e8e32d2e43d9149fac8cea8a5d803571 \
                        size    36045 \
                    github.com/ulikunitz/xz \
                        lock    v0.5.10 \
                        rmd160  ba4a3b2c8049d86688c50648bc06f8969133ee43 \
                        sha256  c237e2956881ae1eee019d3c39b3d8fbff2a8b4631082e156f67272b577f72f8 \
                        size    479677 \
                    github.com/tklauser/numcpus \
                        lock    v0.3.0 \
                        rmd160  ed77627d0966cf13bb74810a76bdbb5141be30b5 \
                        sha256  1320deb41a179280306d7792871098d01c1e7e8d0bfcdb070aae9b7141d5ac1a \
                        size    8809 \
                    github.com/tklauser/go-sysconf \
                        lock    v0.3.9 \
                        rmd160  59870e5f700b0b4ae0f7e88bd33b9d941dcf546d \
                        sha256  58719ee317e2b992aacaa005fedb1e3b22075f5f15a1e1146434eff9f84e164f \
                        size    27915 \
                    github.com/titanous/rocacheck \
                        lock    afe73141d399 \
                        rmd160  f2561517ae9d6f89d8cc086ebc8cc25a146630d5 \
                        sha256  21e5271a84bbc508ae47f5fd9cb4b50b410a4d46b521d2b6a25ec8d1ca8060bb \
                        size    3944 \
                    github.com/thought-machine/go-flags \
                        lock    v1.6.2 \
                        rmd160  3ff807f14bec954a5a958851e57905d1d3d37e59 \
                        sha256  3fb02a1bace777b0f21c8d99a905a5ef4e03e6090648be9a76866af563ebe774 \
                        size    59529 \
                    github.com/theupdateframework/go-tuf \
                        lock    3890c1e7ace4 \
                        rmd160  974753d6158c23f115a6cfc07d92870cb202e684 \
                        sha256  36aff86f3821cf54c5221e971b0c2021bf42bf0dfa71241af83dd6d33e87c51c \
                        size    251276 \
                    github.com/texttheater/golang-levenshtein \
                        lock    v1.0.1 \
                        rmd160  5a5d88c65c92190407a2949dbb600a973af09ffe \
                        sha256  65145e0bea9666b519d6eae0ed080a4ab60dc307a21a7e54a59e228883157225 \
                        size    4856 \
                    github.com/stretchr/testify \
                        lock    v1.8.1 \
                        rmd160  4d80635834e01b3ddb67babdd8de2eac2c5a7587 \
                        sha256  9848272e238f98fc0555b514c4522e70c4df25331b4ee3f9cb9244a04935934e \
                        size    97722 \
                    github.com/sourcegraph/jsonrpc2 \
                        lock    v0.1.0 \
                        rmd160  37fbc63e7ac6aa20618d77a0b070b652ca5eaf81 \
                        sha256  a63345ed1551a5346d46150920bc00f7d60232c526e080ccdce44f0c373baa46 \
                        size    14748 \
                    github.com/sourcegraph/go-lsp \
                        lock    219e11d77f5d \
                        rmd160  f84522552124873cfc9aafc0f715696226eec47a \
                        sha256  2cea1729a0d54224634d9fd90858680a02b3f995f23b232d8f844d623426146a \
                        size    15480 \
                    github.com/sourcegraph/go-diff \
                        lock    v0.6.1 \
                        rmd160  4ca163aad61e43df57f8b30e0abb2ab0be00f80e \
                        sha256  fd75365118ca9362ce9dfd854250d3c1c9c0669434b608f17fd9ec9430ecb39e \
                        size    63364 \
                    github.com/sigstore/sigstore \
                        lock    v1.5.0 \
                        rmd160  a6bc6e3e2916d088ed86fa69bc0be9b8a9b78ac3 \
                        sha256  726cefcbdfdf42ceefc6a030f23063eb9ed899bd24ce5f1c7f2c5c9eb3445da9 \
                        size    227533 \
                    github.com/shirou/gopsutil \
                        lock    v3.21.8 \
                        rmd160  4de017111c3090a81d18fbd43fbbb968415940e4 \
                        sha256  51d02b43c9e774944f8f05acadcdf946821776dd9feb0cc2bd4e2137a147a849 \
                        size    296677 \
                    github.com/ryanuber/go-glob \
                        lock    v1.0.0 \
                        rmd160  d9dda80a3e3a54a3512264aa60e8d293f20c5e1d \
                        sha256  c58e8a7762b827292f173b6f51d5c4d78924fbac816a7f7cccd838055c0a0568 \
                        size    2977 \
                    github.com/prometheus/procfs \
                        lock    v0.8.0 \
                        rmd160  0cd72a082087a0c3dd922a362316063f79364968 \
                        sha256  4047304194f7f2cf99f627a1dae661ec0b3037f34aa07cd4d359e82015debc64 \
                        size    194848 \
                    github.com/prometheus/common \
                        lock    v0.37.0 \
                        rmd160  4b9ab33f6ebadf18c84de43be89633d0adf967d9 \
                        sha256  ed4d3dbcb57018812d44094380bb26c0c331ef6d99d4df13b4ed907aa221bc47 \
                        size    148974 \
                    github.com/prometheus/client_model \
                        lock    v0.3.0 \
                        rmd160  a0b906835c5e39f188c88e71d319eac4a240567d \
                        sha256  54817b98ddf4cde06a2f122c6d811d37ce25cc4f74d0a32bebf5620389c08c00 \
                        size    14955 \
                    github.com/prometheus/client_golang \
                        lock    v1.13.0 \
                        rmd160  4e0a400d5ec02a478288bf851637b98f7fcc04f4 \
                        sha256  23ec964ec317fdfb5fbe481cf0f41d213befaa1693b804bef86934fb478b649c \
                        size    218821 \
                    github.com/pmezard/go-difflib \
                        lock    v1.0.0 \
                        rmd160  fc879bfbdef9e3ff50844def58404e2b5a613ab8 \
                        sha256  7cd492737641847266115f3060489a67f63581e521a8ec51efbc280c33fc991f \
                        size    11409 \
                    github.com/please-build/gcfg \
                        lock    10ea9d657afb \
                        rmd160  b679b3b7f428b5d2b3fc65591c22270e5e730cd7 \
                        sha256  fd6a057ed01611898944bd289bf5562bede78d9f48a5cb616c6c8c8abe040458 \
                        size    42634 \
                    github.com/please-build/buildtools \
                        lock    746673d48318 \
                        rmd160  1b74152e30f8f1be31618d9eae8f7c238f9a7288 \
                        sha256  2d7644651420b3580029f36f886e5f4c6fd892617b62ce88a25f18f77735a090 \
                        size    282761 \
                    github.com/pkg/xattr \
                        lock    v0.4.4 \
                        rmd160  da836ed927c01796aff60d529df567444250a49b \
                        sha256  a81a4ceb419e9a1e9285edf4621776d74424a2890201bae2cef7482b2f2ec869 \
                        size    9401 \
                    github.com/pkg/errors \
                        lock    v0.9.1 \
                        rmd160  dc065c655f8a24c6519b58f9d1202eb266ecda40 \
                        sha256  208d21a7da574026f68a8c9818fa7c6ede1b514ef9e72dc733b496ddcb7792a6 \
                        size    13422 \
                    github.com/pierrec/lz4 \
                        lock    v2.6.1 \
                        rmd160  05ec30e9e7d9ec8ceab0dd663119cb92dffa9df6 \
                        sha256  0c9aff58d4d9187fec2039780107b30f230f8ec645f5972da10e1e5bf8c63b30 \
                        size    40116906 \
                    github.com/peterebden/tools \
                        lock    b2a0db951d2a \
                        rmd160  ea81c97245cceb86abd5048685a20239dc48724a \
                        sha256  88e751083e76de4107fb6ad058ffeba1bdd7e6efe937459cd9f5c909dc7fb882 \
                        size    2200075 \
                    github.com/peterebden/go-sri \
                        lock    v1.1.1 \
                        rmd160  d424303a25ed7d56f3440b6a5e4b5d0b869f394b \
                        sha256  c0288268027181086a7191b6896954f86ae78529ed9f674c80484acf696a49ee \
                        size    9297 \
                    github.com/peterebden/go-deferred-regex \
                        lock    v1.0.0 \
                        rmd160  ea755a848ef1a77730054316697c972c9ee6390f \
                        sha256  cf8406791bc96c7eb76cec554067179ede7e1b249a69d849def21d0d361d38ee \
                        size    7119 \
                    github.com/peterebden/go-cli-init \
                        lock    v5.2.0 \
                        rmd160  23fa145453be0c111b85ee34f75ee9353632b06d \
                        sha256  729cdb9898713fe9aa2e86c0d132c67720baac4fcd8907008105c8aa8e8ccc79 \
                        size    12757 \
                    github.com/pborman/uuid \
                        lock    v1.2.0 \
                        rmd160  491abed705709e8fcb13dad4ac25fe3ca1b3f31a \
                        sha256  b61a3159a3d863f4ded7639e2a0e750b63a977f7f8115d428721709f673690f2 \
                        size    10842 \
                    github.com/opencontainers/go-digest \
                        lock    v1.0.0 \
                        rmd160  8a4108c4ab0b11d2bb6e82021f5a7bb0fdee2e6f \
                        sha256  7c93509fe4e49a67f5e9147534927d5efa662c852e593ab08ab50fc7228ce734 \
                        size    24469 \
                    github.com/oklog/run \
                        lock    v1.1.0 \
                        rmd160  34e52ce7f1d4dc7b7c897a3aaed5c4526b20ad77 \
                        sha256  a29f8513d33780419fc61af66acbb2e84570120caf2df9b18af07a9d03c66b76 \
                        size    7997 \
                    github.com/mostynb/zstdpool-syncpool \
                        lock    v0.0.7 \
                        rmd160  00f71251678b02dcdc214212862958faf29f5c8c \
                        sha256  1a297980ca1d100f202210cc2e39d5e7e840c549bd89f9f21bf921450f6b90d3 \
                        size    6234 \
                    github.com/mitchellh/reflectwalk \
                        lock    v1.0.2 \
                        rmd160  0371e346bfe14926662afff3eeda22ce6dc6d2a4 \
                        sha256  472ea8302bfe36cd5ea5a66cb9ee996d6984ce74bfc9b7c15e763f21687b3eff \
                        size    6863 \
                    github.com/mitchellh/mapstructure \
                        lock    v1.5.0 \
                        rmd160  c838fb22a642081963c8e6f236cdd4c6000bfaf4 \
                        sha256  bd695f63e58f35f07aac6883ac5dc53d44db6cf24caa53efaadcf0842d03d762 \
                        size    30135 \
                    github.com/mitchellh/go-testing-interface \
                        lock    v1.14.1 \
                        rmd160  7b0908c6a2a44bb5dced287f19e993bb7cbb3c4b \
                        sha256  5501ea61887624fe3b89c0aabc887aadfffad64aded054fbe4455ff4dfc341cd \
                        size    2778 \
                    github.com/mitchellh/go-homedir \
                        lock    v1.1.0 \
                        rmd160  44b3985e40e5bbb22d11f8622c340f9ed727ea91 \
                        sha256  024c8a57316c7fbc0eb23cdbfd57f72a74b51beb83d714034d67ee9aba48100c \
                        size    3366 \
                    github.com/mitchellh/copystructure \
                        lock    v1.2.0 \
                        rmd160  401559c8d2db7a6becabf583dca6843e5cd3c5ac \
                        sha256  e6cbd00eca63c91837cd094e89bda52d067163dc5b5db12758b8995c75fd3377 \
                        size    9936 \
                    github.com/matttproud/golang_protobuf_extensions \
                        lock    v1.0.1 \
                        rmd160  e28c4169919e72c08ee6520ad2ce16943d18e40c \
                        sha256  c40d4c38e7dc2a7bae57e3740bb28d463e173d82e4603622d04d01741ff7a083 \
                        size    37197 \
                    github.com/mattn/go-isatty \
                        lock    v0.0.16 \
                        rmd160  dcdf01553caa079315f2293c109de17fc72f0c6b \
                        sha256  391d25a98e2cc92a2ed5c6abd07cde1053411706bb24e5843562931e6085ab46 \
                        size    4693 \
                    github.com/mattn/go-colorable \
                        lock    v0.1.13 \
                        rmd160  c9e8ab9d0773c0984f36235e3c9f8c033552ac1a \
                        sha256  0cd9a951799c1a9f999df56e4b020170fa887456049c274aae6262d9ae3f7424 \
                        size    9778 \
                    github.com/manifoldco/promptui \
                        lock    v0.8.0 \
                        rmd160  b3abf944b60f65b571d2f068df7061e1843473f7 \
                        sha256  e2513c9f17dc87ab347916b523686517d031a2ad8f9c9db32cbbd32fc3bbe49c \
                        size    26838 \
                    github.com/lunixbochs/vtclean \
                        lock    v1.0.0 \
                        rmd160  28eb7432d03d69a0e3484c49341dd876769ebe55 \
                        sha256  f6cbd000c28785924742401aa071061b71e321490cc9bea1cec77bfd2c40eb84 \
                        size    4223 \
                    github.com/letsencrypt/boulder \
                        lock    85aa52084eaf \
                        rmd160  1aaa267097d6ffcfe83a7f25f7c475c782f8e835 \
                        sha256  0eb9c6a190ea33f7e9d0ae72d0c4df9010ebe55651c11b871dca84f2b92725b6 \
                        size    6419942 \
                    github.com/kr/text \
                        lock    v0.1.0 \
                        rmd160  0b3c78459e227170a3b80a0103d87a3eef77ed88 \
                        sha256  5ed970aad0da3cba3cffacdb4d154a162a8968655ee6d6f7b627e71b869efaf6 \
                        size    8691 \
                    github.com/kr/pretty \
                        lock    v0.2.1 \
                        rmd160  eaf5b58a46b962079cbafddbc3ef83bdbf02b31e \
                        sha256  253c4a190c9337800e08aba66b77ea3db0835e3ae61289d80093995a649eb7ae \
                        size    8769 \
                    github.com/klauspost/cpuid \
                        lock    v2.0.12 \
                        rmd160  e4fc07a2cfad3b9da39ebd0c41fd779938ec8924 \
                        sha256  88ebd59c61cad2d99148d8deecc758ddb70358fd6ce964e4edd70fabc0aad76f \
                        size    343280 \
                    github.com/klauspost/compress \
                        lock    v1.15.11 \
                        rmd160  a661ea501f73f3ed730b2036d139aff74f5a4e51 \
                        sha256  8298d3a159ebf8ddf6033318f19a12597c29b2eadec5469c59e8180af0679d05 \
                        size    36199250 \
                    github.com/karrick/godirwalk \
                        lock    v1.16.1 \
                        rmd160  8fb4d41a69f68133784172f95c03af798b07eaab \
                        sha256  5be9a6cb67201740c0bd74ee3b62494cac2b0c47695efdc010e7be25c2b29d74 \
                        size    27134 \
                    github.com/juju/ansiterm \
                        lock    9283cdf370b5 \
                        rmd160  785405f518db9cc4f67ab2fc0282355d6334d6c2 \
                        sha256  54d6e5e0f37d006ff9dc7a11ac8023be477b650f687feeb7d324d58842c9e199 \
                        size    15423 \
                    github.com/jstemmer/go-junit-report \
                        lock    v2.0.0 \
                        rmd160  aee094273ab588f126d9c2a1f3e93e57cb0d13a7 \
                        sha256  acb54baae5cd331ed94f027d20a46fb6daa781938dce1a3e9d72de3f45c657a8 \
                        size    37839 \
                    github.com/jmhodges/clock \
                        lock    880ee4c33548 \
                        rmd160  a7f9e32938f5cdcedacb93cdd4d77206ff065082 \
                        sha256  63d7afde7e945287224920e8f23805554d3f3cd5e48d41a28aa90c83d80179db \
                        size    5767 \
                    github.com/jellydator/ttlcache \
                        lock    v2.11.1 \
                        rmd160  f102bde18e8595d2bd3d1b7cb7c8f2700e11d476 \
                        sha256  489a707366bdd02dd101cacb3d4ad56b85ae192a132d3a9e8b63753116b31698 \
                        size    18742 \
                    github.com/honeycombio/libhoney-go \
                        lock    v1.16.0 \
                        rmd160  81d59f54eb569fe4eeddca11996e5fa2be051739 \
                        sha256  60fd9ce80c33f78077de6733668177abe87476881025cfa4390100f5addcd737 \
                        size    63559 \
                    github.com/honeycombio/beeline-go \
                        lock    v1.10.0 \
                        rmd160  7deee32495208576a95a0915d49c90332b85af56 \
                        sha256  2fac33c85e8dc6981a476576f76a79925fbe96f8c0ba55918b43bf75b3972dc9 \
                        size    109840 \
                    github.com/hashicorp/yamux \
                        lock    v0.1.1 \
                        rmd160  2d4e32b38cea4c3be4c23c343cd5061eedab6442 \
                        sha256  513c96e8e381749193262cc7e55eff69a26237be9a4959d3fee8a57964b3f438 \
                        size    26019 \
                    github.com/hashicorp/vault/sdk \
                        lock    v0.6.1 \
                        rmd160  145db43dbd03aafc369adccb7c0d133d6ec432a5 \
                        sha256  092b3b2240b42a1721da08be541b7c6692b01de84aa6c03c03616233809ded99 \
                        size    4666516 \
                    github.com/hashicorp/vault/api \
                        lock    v1.8.2 \
                        rmd160  ef23d4f6ddba22f0a8d18465aba4fa0add591bd6 \
                        sha256  a66a24ff41c18044b894c98f4e87f61a4876dd2785e77474276d03eecf7b5230 \
                        size    20976331 \
                    github.com/hashicorp/hcl \
                        lock    v1.0.0 \
                        rmd160  ad8d0b523bb708fd6ae77df8bb414c103a75aa92 \
                        sha256  4fc0e87ac9d3d6cd042f044df2db2703bed569051fb8c179d505edeb4433e96e \
                        size    70636 \
                    github.com/hashicorp/golang-lru \
                        lock    v0.5.4 \
                        rmd160  833d8d87b84f13bc545ecffff9358a19671d185a \
                        sha256  c358bb5050adae91e443f59ff70b7c0ad6906fc4abe1b30066bf0c408fdf9b5c \
                        size    13435 \
                    github.com/hashicorp/go-version \
                        lock    v1.6.0 \
                        rmd160  e2738a78472a98f067520abd0833b64b83887ac3 \
                        sha256  f13b1e81ac2386acd975ef942abf70ecbcd29fa731820a102c2e8287fe881bee \
                        size    15899 \
                    github.com/hashicorp/go-uuid \
                        lock    v1.0.3 \
                        rmd160  5bbc605770e6b5798ce16f2adbdadb666e9ca750 \
                        sha256  0c5833dde295985c0c48fd7a3e18b4111426645c106a345d37366a66ee33b75d \
                        size    7100 \
                    github.com/hashicorp/go-sockaddr \
                        lock    v1.0.2 \
                        rmd160  ca8704f673762c0676a0717033068387c6732755 \
                        sha256  57878fb9ed5d2f141cb989dbd7916b48bf130a9dee81d3590d61d8d82428cf99 \
                        size    663398 \
                    github.com/hashicorp/go-secure-stdlib \
                        lock    v0.1.0 \
                        rmd160  d38709e07b9a14e0213de8184e8ea6f9a5a8b20b \
                        sha256  9c6e7a9d82c989b0d062667ac3be2ae9f57f35a40d7b12c0abd95ed246133f58 \
                        size    165463 \
                    github.com/hashicorp/go-rootcerts \
                        lock    v1.0.2 \
                        rmd160  976240c00caad02d53f7ea241f3097285e4f468e \
                        sha256  06e5f6bb70a3e21c884c99b969c2d0965b1b49c953363de6e6b0b80591b4e6df \
                        size    12248 \
                    github.com/hashicorp/go-retryablehttp \
                        lock    v0.7.2 \
                        rmd160  03a14b940c8c41683e0c5699e84847c8412e219e \
                        sha256  2a9d702ba50089da3625d8f7f97f4e6054fc1a66e971343aba482f1ffd1cac2d \
                        size    21356 \
                    github.com/hashicorp/go-plugin \
                        lock    v1.4.6 \
                        rmd160  cf1ad123f6fa73d32b01b178f3b632a2acc600e3 \
                        sha256  505bb5265da8adfd07eafb86194d16bd61dcf71dc2e8188ed0858790cf960d4a \
                        size    94702 \
                    github.com/hashicorp/go-multierror \
                        lock    v1.1.1 \
                        rmd160  94493cc3074dc39be0de76f04fa2a44a405d0a42 \
                        sha256  52e986cca6d6335bfcd23b4867f884311cfb5ca060325496b6692029797d64e2 \
                        size    13805 \
                    github.com/hashicorp/go-immutable-radix \
                        lock    v1.3.1 \
                        rmd160  906acb97a748c9198f6a34d220e22d58b42bf755 \
                        sha256  01c794c4dea0c1db0df3299fda894967893c07954189238c8d2d73e53177ff85 \
                        size    27614 \
                    github.com/hashicorp/go-hclog \
                        lock    v1.3.1 \
                        rmd160  ab5400782c5710c57f8ee93fbab2cb87ba9c7726 \
                        sha256  ece65eb12835e6e86e0551c0bd4d6d02666aca788b7805a56aa5c09ae5033f44 \
                        size    30431 \
                    github.com/hashicorp/go-cleanhttp \
                        lock    v0.5.2 \
                        rmd160  18348882947b87155ec4391e1ea40d17a5314237 \
                        sha256  8f1a23af40fcc070a83fe3a32292f6607b19fc351d1b400778a18e8b8efc63e6 \
                        size    8091 \
                    github.com/hashicorp/errwrap \
                        lock    v1.1.0 \
                        rmd160  25e655fc958685dd949900eea8c3d97f33d85eab \
                        sha256  f3e47c96ca16c7360f7d3fd3a57d8861be5835a5d5a9d9d1dc2ec10ae4a1208d \
                        size    8586 \
                    github.com/grpc-ecosystem/go-grpc-middleware \
                        lock    v1.3.0 \
                        rmd160  d38c0c95949e12a7a823c673793d607d0c24b093 \
                        sha256  1f7dba59d6613cc59533b0761b0401987701878a9af528d07e47017f25a1bb1c \
                        size    103779 \
                    github.com/gorilla/websocket \
                        lock    v1.4.1 \
                        rmd160  fabb50c4c2297eb4485ccc1abb5ead16c239e26f \
                        sha256  79182d9e15e4dbd709c7d360245e25445628e0d111472a9809fc5ba6327af646 \
                        size    54230 \
                    github.com/googleapis/gax-go \
                        lock    v2.7.1 \
                        rmd160  861e3c57acd0c7a4d268be102b3922e30a858dfe \
                        sha256  f0e9787f69edcea35c1d4865d7056cc219de2821ce555a8d2329d7bc1da9798f \
                        size    32850 \
                    github.com/googleapis/enterprise-certificate-proxy \
                        lock    v0.2.3 \
                        rmd160  f45c3a20702f77a3cec4797e6b39ad89326a17d5 \
                        sha256  f071c314cbcf7a0cbb1fb759a93f3bf8e64266bf1209ecaacaa9eb61cf98442b \
                        size    31969 \
                    github.com/google/uuid \
                        lock    v1.3.0 \
                        rmd160  300ea34c54ab7ce9d2a4bbd84a4fb49f11db02f8 \
                        sha256  ef8b7d74d99c8abd9706909eb3bbd063460d1970fbf62619599b78092b8687db \
                        size    16215 \
                    github.com/google/shlex \
                        lock    c34317bd91bf \
                        rmd160  e9a28aae4f27edc417d86c9013ed985880df66c8 \
                        sha256  0c3bf5da1111371bd986caed044034face394904c4a7d119dd5c4a4aaf87910a \
                        size    7235 \
                    github.com/google/go-containerregistry \
                        lock    v0.12.1 \
                        rmd160  a0289c3147969b8eedc2ae3f03e9881adaa179a2 \
                        sha256  26263ff3066d96663ecb7486c4b7a1190bfe443dd828ea20f86f993381822d08 \
                        size    4326570 \
                    github.com/google/go-cmp \
                        lock    v0.5.9 \
                        rmd160  9832ae80123461baed8aa20e830199c0e21e337b \
                        sha256  3058d20d61f03aa05fca0fc07acb8c50850c68086998c542857aec7ad1529482 \
                        size    104431 \
                    github.com/golang/snappy \
                        lock    v0.0.4 \
                        rmd160  23c095b7e2bc6f5a978d771e4ecc9f7b0f204491 \
                        sha256  6a2d69e63124670c8b8105fb34d32f3f34f6816f93bf5a6e28f85c428c5b40ae \
                        size    66136 \
                    github.com/golang/protobuf \
                        lock    v1.5.3 \
                        rmd160  b4e09ad842f6dcd3aea36b28ec64d6d9563fd1d8 \
                        sha256  12e830fab630cabd279fca57e7089eeb1556e2c22b58eee64bb21bd3c8dfc706 \
                        size    171856 \
                    github.com/golang/groupcache \
                        lock    41bb18bfe9da \
                        rmd160  dba4526dc11102f7cfc3ee7be23cb1416793e35b \
                        sha256  03b46be967afa501b74a1bf72211b08d6e8f6b2a3b42335105480b6df6e51980 \
                        size    26110 \
                    github.com/golang/glog \
                        lock    v1.1.0 \
                        rmd160  6c04de4a1b5272d66da8db86a474ed85f1d1e647 \
                        sha256  b4bc8c8824ffbd3dd5f1237eb5956f66fbefc4f9793d3764bcfdfe57ce9c75ca \
                        size    29146 \
                    github.com/golang-jwt/jwt \
                        lock    v4.4.2 \
                        rmd160  8ee574c3fd8449b4701a21e3d4ff94fa0d4c5242 \
                        sha256  83a872989dcdc5f105257259f3456ecb254bda1ab4c821585a4b60a7c56a58be \
                        size    51417 \
                    github.com/go-test/deep \
                        lock    v1.0.8 \
                        rmd160  ca518b4652f1d9c1be2a4353daa01aed8e15e1e2 \
                        sha256  a4c3587f105c56e6f31c180540362f695d25acadc3b5dfa44f7aa2067facfd58 \
                        size    11719 \
                    github.com/go-ole/go-ole \
                        lock    v1.2.5 \
                        rmd160  f7f27856c075157805127a942986a32c4419870d \
                        sha256  de7c73fc49bb9e35121fe7fde41b03928745d45e08253542e2d5d37b9acfff71 \
                        size    52044 \
                    github.com/fsnotify/fsnotify \
                        lock    v1.5.1 \
                        rmd160  c99fbad44a371ce38eb2bd5c6ef70fb4537952e3 \
                        sha256  699405dfda2fe02a305bee66f58046adb43f426ac905f85d80710e36846b3768 \
                        size    32714 \
                    github.com/fatih/color \
                        lock    v1.13.0 \
                        rmd160  0c56533948a292eb8c5181e9a88a45fbd1267bf5 \
                        sha256  a65b114bfe507384e1660730803ffb4437c63a24dd11a5d7f61c77f048caa55f \
                        size    10828 \
                    github.com/facebookgo/muster \
                        lock    fd3d7953fd52 \
                        rmd160  7337d0708b11ab355a36c870849a806963435c2f \
                        sha256  72b160c26ca09185d6aff0c9f2cacc1beb47262fb84845d40ef2bd622bf7a69c \
                        size    6374 \
                    github.com/facebookgo/limitgroup \
                        lock    6abd8d71ec01 \
                        rmd160  362069556f39385369e2e4df0c0957ed8f6e7a70 \
                        sha256  1435ce4f7ce2debb01cbaba8c04d1a1e60a69a8d92221f35ef61f313d7848740 \
                        size    3316 \
                    github.com/facebookgo/clock \
                        lock    600d898af40a \
                        rmd160  aab4c90ceeeb688642a5463be888a38574c22bde \
                        sha256  07eaf6b3fdba8d839f67780abadb029cd4cf6aaea87e4be857f52df6645f5454 \
                        size    6391 \
                    github.com/dustin/go-humanize \
                        lock    v1.0.0 \
                        rmd160  e8641035159ea3e8839ee086f01f966443956303 \
                        sha256  e45e3181c07b3e2dad8e1317e91a5bbbee4845067e3e3879a585a5254bc6a334 \
                        size    17273 \
                    github.com/djherbis/atime \
                        lock    v1.1.0 \
                        rmd160  895c7d4dd8841c7dde34e2842715d75022fdce08 \
                        sha256  65d7b3933a59b2dc7ff25ee141e66680dd2a6142bdd84048b0430955296ef08d \
                        size    3142 \
                    github.com/dimchansky/utfbom \
                        lock    v1.1.1 \
                        rmd160  182248653dc487311900d188180c74962909bd76 \
                        sha256  203f7bd33e56dfc3d1764493615e3171f4fb3edf5ee234628123e464406e77b1 \
                        size    8497 \
                    github.com/davecgh/go-spew \
                        lock    v1.1.1 \
                        rmd160  7c02883aa81f81aca14e13a27fdca9e7fbc136f7 \
                        sha256  e85d6afa83e64962e0d63dd4812971eccf2b9b5445eda93f46a4406f0c177d5f \
                        size    42171 \
                    github.com/coreos/go-semver \
                        lock    v0.3.0 \
                        rmd160  c4586d02e1c2747dbc72aab4bc10e0cc32703b03 \
                        sha256  1bbfd8b72c657327bc3d347ca26567d3de99452354eb999695f5ecb3db8ec1fa \
                        size    10670 \
                    github.com/chzyer/test \
                        lock    a1ea475d72b1 \
                        rmd160  61f83d79b356cde63a27df0f2832ef92fcbc216d \
                        sha256  98d0c7d1dec438459e31886d65190bb45f70c4ed73e35f5ab2f3b8de582ea309 \
                        size    4007 \
                    github.com/chzyer/readline \
                        lock    2972be24d48e \
                        rmd160  933f32b684d0af4b8970d964d610918a9f181df6 \
                        sha256  f5771c6a3d97166a9536f8a45e85e1c40aed9b02089e395d2f4131681cbf692f \
                        size    36826 \
                    github.com/chzyer/logex \
                        lock    v1.1.10 \
                        rmd160  105d839f798ba0c3e27b3db4e790d9d21a928029 \
                        sha256  947e61095044d310b0ad92f10ac77c36eaa3c3e2e6181e87428ad10c20930ba3 \
                        size    4351 \
                    github.com/cespare/xxhash \
                        lock    v2.2.0 \
                        rmd160  17d6143308fd7f2ccf9b885b19a2445a612ce013 \
                        sha256  d491baceb567c1fcc6eae97991816169f798ac2bfc9f62224bd6ad63b1a4e60e \
                        size    12348 \
                    github.com/cenkalti/backoff \
                        lock    v3.2.2 \
                        rmd160  33d6dd55a272ba220ed8fe524342a87a87fbdd1c \
                        sha256  0e43f97e0a191009eb2e569fe5c807b77ad33c9f901e904af121cdf1e9be1912 \
                        size    9249 \
                    github.com/beorn7/perks \
                        lock    v1.0.1 \
                        rmd160  c6c5c7fd2132f01925c7fccd9d27c9d7a80f2adb \
                        sha256  78da4421e9f9fa2ee5e3855bdd31cfb04c7e823d9c0ec385cc2c008132d98b96 \
                        size    10874 \
                    github.com/bazelbuild/remote-apis-sdks \
                        lock    e62cf9b8696a \
                        rmd160  9ec7d58a6bfff312d027a3814182dd87ab429338 \
                        sha256  2b1ed993caa305fcae6796151c653bd1e12dccb000b2a5c30dc97da62c46bed5 \
                        size    197533 \
                    github.com/bazelbuild/remote-apis \
                        lock    0ecef08215cf \
                        rmd160  e325808081aa9372df4f4fad2ac1f51e4363390f \
                        sha256  ccb622d3f5d6c90a325994a7a18ab438a3cda4ffa199031a2053f4be70698791 \
                        size    98946 \
                    github.com/aws/smithy-go \
                        lock    v1.13.5 \
                        rmd160  b26f3f8fba46a8fd5db8187e965bb93bd303e3e7 \
                        sha256  62bb578f51022f35804fbe060e66579e7e20adb75681f4e522ef35a6832a9417 \
                        size    327362 \
                    github.com/aws/aws-sdk-go-v2/service/sts \
                        lock    v1.17.6 \
                        rmd160  fe753b92389bbd2190892393f803bb179d68aa56 \
                        sha256  7367751f962c76e5d5f6785e99f7f4057df4d855de0187e3abbfc685151e9744 \
                        size    33440406 \
                    github.com/aws/aws-sdk-go-v2 \
                        lock    v1.17.2 \
                        rmd160  9aa3d2c9262fcbdde16d3d01c801d4c472f648f8 \
                        sha256  169a9e1e91370113fa12017ee86ad96a139484bd905d5ff43fb2e89676d80845 \
                        size    32292263 \
                    github.com/armon/go-radix \
                        lock    v1.0.0 \
                        rmd160  fbaf4605ffc4654bdd5b8a3b60d7f2b65333d1b3 \
                        sha256  f9a27dc2a25030e5a6a5334dd82697e0494e5719ec4cfdc59b6ba903f99c9400 \
                        size    5982 \
                    github.com/armon/go-metrics \
                        lock    v0.4.1 \
                        rmd160  8fb881d7259244e3ad13b74515a585bef6b68d79 \
                        sha256  5e288e25c2f5b52d21bf39cf3a1c076bf8a9a0570f1a286cac930c06d49bb2de \
                        size    38319 \
                    github.com/alessio/shellescape \
                        lock    v1.4.1 \
                        rmd160  669d9a26af060752e544e09551b8835dc89b336a \
                        sha256  ab26daceb19d4973dd1bf37105473f8d27697b5a04b124d790fd45124450b9a2 \
                        size    7552 \
                    github.com/StackExchange/wmi \
                        lock    v1.2.1 \
                        rmd160  f02f859c7021ddd8422f78793d3e3001c85565d2 \
                        sha256  e1d463fd14dd07f40914b7ce14cfa4d453fec5292601fea27af24e2bb8bb470c \
                        size    12455 \
                    github.com/ProtonMail/go-crypto \
                        lock    2c5829bbf927 \
                        rmd160  2382eaa948af245bf38e6c3110a37472627bc870 \
                        sha256  e2c6f061652988b98b9ec77880c37408b6ec96d3c141eb7aea8d3f0be1be0891 \
                        size    308531 \
                    github.com/Masterminds/semver \
                        lock    v3.1.1 \
                        rmd160  ef0a447415b81d00561b3559a38aebfbdf95b300 \
                        sha256  e3f9518048841bde91680be27cb32cd1ac7d114fb99719855ecd5777bd221f98 \
                        size    24515 \
                    github.com/Azure/go-autorest \
                        lock    v14.2.0 \
                        rmd160  6f33795fd18d49ea2f18d03c292bacc9a798ecf1 \
                        sha256  b7ebd1b94ca0fce90568df611dfa16af34617ccd4df09c2d82ed40306783cf34 \
                        size    167830 \
                    github.com/Azure/azure-sdk-for-go \
                        lock    v67.1.0 \
                        rmd160  ced0e368374660182404655d677749c2ae35dd38 \
                        sha256  08166e905ae1fb64de27b03d86a0832f105e1143f440ef53d7fc85caa0692b2f \
                        size    46411707 \
                    cloud.google.com/go \
                        repo    github.com/googleapis/google-cloud-go \
                        lock    v0.110.0 \
                        rmd160  7184f025cea79177c1729ccb1b6aa6fd4011f496 \
                        sha256  9a4a3424a7eaadfc21a21c4be8660823f603fa3b04b5bd43670c5a94e0e3cdc5 \
                        size    19965358
```
</details>

**Comment by amake** [comment]
Also I should note that I already released an update to go2port that has some changes that make things a little bit easier to diagnose:

- Instead of `size 14`, unresolvable dependencies will be `size 0` (also checksums will be 0)
- Warnings about unresolvable dependencies on stderr

**Comment by halostatue** [comment]
Thank you for your response and the updated release. I’ll look at it more in depth this evening, but your explanation makes sense.

**Comment by halostatue** [comment]
So, I finally had a chance to try this. The resulting portfile still doesn't work — but that's because I think there's something fundamentally broken about the golang portgroup. The tags for the AWS tree files are specific to the sub-SDK being looked at — for STS, it should be trying to download `service/sts/v1.17.6`, but it is trying to download `service/v1.17.6`.

I spent a bit of time reading [trac:61192](https://trac.macports.org/ticket/61192) and then looking at what `go mod vendor` and `go mod download` do … and I don't see a clean way around this without lifting about ~30% of what `go mod` subcommands do. It would be nice if Go made  the code behind the `go mod` subcommands available as library functions. Barring that and/or interest in someone hosting that code into something that `go2port` or other tools could use, I suspect that the best choice for MacPorts would be to run builds pointing to its own module proxy, something like [athens](https://github.com/gomods/athens) in `sync` or `async_redirect` [download mode](https://docs.gomods.io/configuration/download/).

The next best choice would be to have maintainers run `go mod vendor` and tar up the resulting vendor directory and make that available somehow to the distfiles server. That "somehow" carries a lot of weight, especially since there would be a security risk involved.

**Comment by mascguy** [comment]
I just experienced the same issue, when trying to generate a new port.

In terms of handling the package resolution, I *think* you might be able to utilize the `mod` module to simplify the code. In addition, that might also help eliminate the issues.

- https://pkg.go.dev/golang.org/x/mod

I'm not a Go expert, but some quick Googling provides some sample code for working with that:

- https://www.reddit.com/r/golang/comments/p25zwx/how_can_i_parse_the_gomod_and_gosum_files_to_get/

**Comment by amake** [comment]
> I _think_ you might be able to utilize the `mod` module

Honestly, the only response I can give to this is "patches welcome".

**Comment by mascguy** [comment]
> > I _think_ you might be able to utilize the `mod` module
> 
> Honestly, the only response I can give to this is "patches welcome".

Sounds good, perhaps I'll dig into this over the coming days.

Also, if you're interested in the example I'm working on, take a look at this new port for `ollama`:

https://github.com/macports/macports-ports/pull/27437

**Comment by halostatue** [comment]
I still think that the `go` portgroup should be changed to, as much as possible, pull the source required from the Go [module index](https://index.golang.org) (specifically the [proxy](https://proxy.golang.org/) for most items), which will give _smaller_ packages. I ran into cases where pg downloaded the same ~30Mib repo a dozen times with `go.vendors`.

This would absolutely be a breaking change, but I think it would result in faster source-build times for go projects. It would also require further updates to `go2port` to support the different versions.

**Comment by amake** [comment]
Patches welcome!

**Comment by amake** [comment]
Relevant information: https://words.filippo.io/gosum/
